@startuml
'https://plantuml.com/class-diagram

interface ICoreService {}

interface IProfileService {
    + events
    getAllReady()
    getAllErrors()
    setProfileURIs()
    getProfileURIs()
    getProfiles()
}

interface IProfile {
    + events
    + id
    getIsReady(): boolean
    getErrors(): string[]
    getDefinition(): ProfileDefinition | null
}

class ProfileFactory {
    createProfileFromURI(profileURI: string): Promise<IProfile>
}

note top of ProfileFactory: Takes care of resolving the profileURIs to profile crates

interface IProfileFactoryStrategy {
    name
    isApplicable()
    createProfileFromProfileCrate()
}

ICoreService *-- "1" IProfileService: profileService
IProfileService *-- "*" IProfile: profiles
IProfile *-- "1" ProfileDefinition: definition
ProfileFactory --> "*" IProfileFactoryStrategy: STRATEGIES

IProfileFactoryStrategy ..> IProfile: <<creates>>
IProfileService ..> ProfileFactory: <<uses>>

class ProfileDefinition {
    @id: String
    name: String
    description?: string
    specification: RO_CRATE_SPEC
    version?: string
}

class ProfileClass {
    @id: string
    specializationOf?: string
    name?: string
    label?: string
    description?: string
    minCount?: number
    maxCount?: number
}

class ProfileProperty {
    @id: string
    specializationOf?: string
    name?: string
    label: string
    description?: string
    minCount?: number
    maxCount?: number
    domainIncludes: IReference[]
    rangeIncludes?: IReference[]
    value?: EntityPropertyTypes
    options?: EntitySinglePropertyTypes[]
}

ProfileDefinition "1" *-- "*" ProfileClass: classes
ProfileDefinition "1" *-- "*" ProfileProperty: properties

@enduml