@startuml
'https://plantuml.com/sequence-diagram

autonumber

Consumer ->> SchemaService: resolve(id)
SchemaService -> EntityFinder: get(id)
return result

alt Ad-hoc def found
    alt Ad-hoc term is specialization
        SchemaService ->> SchemaService: resolve(result.specializationOf)
    else As-hoc term is self-contained
        SchemaService -->> Consumer: term
    end
    else
    SchemaService ->> SchemaWorker: resolve(id)
    return term
    SchemaService -->> Consumer: term
end

@enduml