@startuml

package ui {
    component EditorPage
    component EditorLayout
    component CoreProvider

    note right of CoreProvider
        Orchestrates Core
        and Persistence components
    endnote

    EditorLayout *-- EditorPage
    CoreProvider <.. EditorLayout
}

package persistence <<unstable>> {
    component Persistence
}


package core <<stable>> {
    component Core
    interface IPersistenceService
}


Core --( IPersistenceService
IPersistenceService -- Persistence

Core <.. CoreProvider
Persistence <.. CoreProvider

@enduml