@startuml

package core {
    interface IPersistence

    interface ICoreService {
        addFileEntity()
        addFolderEntity()
        changeEntityIdentifier()
        deleteEntity()
    }

    interface IPersistenceAdapter {
        getMetadataGraph()
        getMetadataContext()
        updateMetadataGraph()
        updateMetadataContext()
    }

    ICoreService ..> IPersistence
    ICoreService *-- IContextService
    ICoreService *-- IMetadataService

    interface IContextService {
        - context
        + events
        getSpecification()
        getUsesFallback()
        getCustomContextPairs()
        removeCustomContextPair()
        addCustomContextPair()
    }

    interface IContextResolverService {
        resolve(id)
        reverse(id)
    }

    IContextResolverService "resolver" --* IContextService

    interface IMetadataService {
        - graph
        + events

        getEntities()
        addEntity()
        updateEntity()
        changeEntityIdentifier()
        deleteEntity()
    }

    IPersistenceAdapter <.. IMetadataService
    IPersistenceAdapter <.. IContextService
    IPersistenceAdapter ..> IPersistence
}

@enduml