@startuml

package persistence <<unstable>> {
    component Persistence
}


package core <<stable>> {
    component Core
    interface IPersistenceService
}


Core --( IPersistenceService
IPersistenceService -- Persistence

@enduml